language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    include:
        - php: 7.0
        - php: hhvm-stable
          sudo: required
          dist: trusty
        - php: nightly

    allow_failures:
        - php: hhvm-stable
        - php: nightly

    fast_finish: true

before_script:
    - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
    - composer self-update
    - composer global require --prefer-source phpunit/phpunit:"^5.3.0" satooshi/php-coveralls:^1.0.0
    - composer install --prefer-source
    - mkdir -p ./build/logs

script:
    - ~/.composer/vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''coverage_clover: build/logs/clover.xml'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-stable" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ~/.composer/vendor/bin/coveralls -v; fi;'

notifications:
    email: false
